### ISSUE TITLE
Weird characters when no ports are specified

### ISSUE THREAD

**Issue by gwynbleide** [shapedthought/portsApp#5]
Hello,

some ports are not defined, for example for SureBackup. It shows weird characters instead it should say nothing or "n/a".

![image](https://github.com/user-attachments/assets/3b8dd1e4-03d3-4695-b21a-ac1d4f7e058f)

Thank you

**Comment by shapedthought** [comment]
Thanks for letting me know, I'm having to go through the database to clean things up slowly.

**Comment by shapedthought** [comment]
I've updated the database so those should have gone now.
